# Generated by Django 3.0.1 on 2020-05-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user/image/default.png', upload_to='user/images/%Y/%m/%d/'),
        ),
    ]
