# Generated by Django 3.0.1 on 2020-05-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200501_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/user/default.png', upload_to='images/user/%Y/%m/%d/'),
        ),
    ]
