# Generated by Django 3.0.1 on 2020-05-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200501_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/user/default.svg', upload_to='images/user/%Y/%m/%d/'),
        ),
    ]
