# Generated by Django 3.0.7 on 2020-07-19 12:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('content', ckeditor.fields.RichTextField(default='', max_length=1500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/discussion/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('Apparels & Accessories', 'Apparels & Accessories'), ('Automobiles ', 'Automobiles '), ('Beauty & Health', 'Beauty & Health'), ('Books & Learning', 'Books & Learning'), ('Business & Industrial', 'Business & Industrial'), ('Computer & Peripherals', 'Computer & Peripherals'), ('Electronics', 'Electronics'), ('Events & Happenings', 'Events & Happenings'), ('Home, Furnishing & Appliances ', 'Home, Furnishing & Appliances '), ('Mobile & Accessories ', 'Mobile & Accessories '), ('Music Instrument', 'Music Instrument'), ('Pets & Pet Care', 'Pets & Pet Care'), ('Real Estate ', 'Real Estate '), ('Services', 'Services'), ('Sports & Fitness', 'Sports & Fitness'), ('Toys & Video Games', 'Toys & Video Games'), ('Travel, Tour & Packages', 'Travel, Tour & Packages'), ('Others', 'Others')], default='Others', max_length=70)),
                ('tags', models.CharField(blank=True, max_length=70)),
                ('views', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votes', models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField(max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.Discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
