# Generated by Django 3.0.1 on 2019-12-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
