# Generated by Django 3.0.1 on 2019-12-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20191223_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='discussion_img/%Y/%m/%d/'),
        ),
    ]
