# Generated by Django 3.0.1 on 2020-04-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_auto_20191224_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='category',
            field=models.CharField(default='test_category', max_length=70),
        ),
    ]
