# Generated by Django 3.0.1 on 2020-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_discussion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='image',
            field=models.ImageField(default='user/image/default.png', upload_to='user/image'),
        ),
    ]
