# Generated by Django 3.0.1 on 2020-05-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_discussion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='image',
            field=models.ImageField(blank=True, default='user/image/default.png', upload_to='user/image'),
        ),
    ]
