# Generated by Django 3.0.1 on 2020-05-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0007_remove_discussion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/discussion/%Y/%m/%d/'),
        ),
    ]
