# Generated by Django 3.0.1 on 2020-05-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0008_auto_20200501_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.CharField(default='test', max_length=70),
        ),
    ]
