# Generated by Django 3.0.6 on 2020-05-09 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0009_auto_20200507_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.CharField(default='others', max_length=70),
        ),
    ]
