# Generated by Django 3.0.6 on 2020-05-09 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0010_auto_20200509_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
