# Generated by Django 3.0.6 on 2020-05-11 14:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0012_discussion_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
