# Generated by Django 3.0.6 on 2020-05-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0013_auto_20200511_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='tag',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December'), ('Others', 'others')], default='Others', max_length=70),
        ),
    ]
