# Generated by Django 3.0.6 on 2020-05-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0014_auto_20200512_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December'), ('Others', 'Others')], default='Others', max_length=70),
        ),
    ]
