# Generated by Django 3.0.6 on 2020-05-12 16:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0017_auto_20200512_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
