# Generated by Django 3.0.6 on 2020-05-14 10:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0019_auto_20200514_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=130),
        ),
    ]
