# Generated by Django 3.0.6 on 2020-05-14 10:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0020_auto_20200514_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
