# Generated by Django 3.0.6 on 2020-05-14 10:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0022_auto_20200514_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
    ]
