# Generated by Django 3.0.6 on 2020-05-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0023_auto_20200514_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Apparels & Accessories', 'Apparels & Accessories'), ('Automobiles ', 'Automobiles '), ('Beauty & Health', 'Beauty & Health'), ('Books & Learning', 'Books & Learning'), ('Business & Industrial', 'Business & Industrial'), ('Computer & Peripherals', 'Computer & Peripherals'), ('Electronics', 'Electronics'), ('Events & Happenings', 'Events & Happenings'), ('Home, Furnishing & Appliances ', 'Home, Furnishing & Appliances '), ('Mobile & Accessories ', 'Mobile & Accessories '), ('Music Instrument', 'Music Instrument'), ('Pets & Pet Care', 'Pets & Pet Care'), ('Real Estate ', 'Real Estate '), ('Services', 'Services'), ('Sports & Fitness', 'Sports & Fitness'), ('Toys & Video Games', 'Toys & Video Games'), ('Travel, Tour & Packages ', 'Travel, Tour & Packages '), ('Others', 'Others')], default='Others', max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discussions.Category'),
        ),
    ]
