# Generated by Django 3.0.6 on 2020-05-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0024_auto_20200517_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Others', max_length=70),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.Category'),
        ),
    ]
