# Generated by Django 3.0.7 on 2020-06-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0028_auto_20200523_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.CharField(choices=[('Apparels & Accessories', 'Apparels & Accessories'), ('Automobiles ', 'Automobiles '), ('Beauty & Health', 'Beauty & Health'), ('Books & Learning', 'Books & Learning'), ('Business & Industrial', 'Business & Industrial'), ('Computer & Peripherals', 'Computer & Peripherals'), ('Electronics', 'Electronics'), ('Events & Happenings', 'Events & Happenings'), ('Home, Furnishing & Appliances ', 'Home, Furnishing & Appliances '), ('Mobile & Accessories ', 'Mobile & Accessories '), ('Music Instrument', 'Music Instrument'), ('Pets & Pet Care', 'Pets & Pet Care'), ('Real Estate ', 'Real Estate '), ('Services', 'Services'), ('Sports & Fitness', 'Sports & Fitness'), ('Toys & Video Games', 'Toys & Video Games'), ('Travel, Tour & Packages', 'Travel, Tour & Packages'), ('Others', 'Others')], default='Others', max_length=70),
        ),
    ]
