# Generated by Django 3.0.7 on 2020-07-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0031_auto_20200716_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/discussion/%Y/%m/%d/'),
        ),
    ]
